### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by NextGenerationHackers** [Julianty123/Account-Creator#2]
It doesn't actually create accounts. I use the slider to create 50 Gmail accounts. According to the chromium page, it created them all, however, when trying to log into ANY of them via a real browser like Chrome, none of them say the E-mail is Recognized.

If it attempts to create them, there should be a SUCCESS or a Failure page or a: this email already exists, and if that is the case; you should make it to where it logs it and possibly cross out the possible Email account. 

Besides, the initial not creating them; the GUI was nice, and I wondered the size it was downloading, so if you can suggest the size of the download File; so that I can expect the length of time it will be done. These are just some suggestions.

**Comment by Julianty123** [comment]
Thanks for the suggestion, yes! i'm still very beginner in this
